//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicShopClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", ConfigurationName="ServiceReference1.MusicShopWebService")]
    public interface MusicShopWebService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllCategoriesRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllCategoriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MusicShopClient.ServiceReference1.getAllCategoriesResponse getAllCategories(MusicShopClient.ServiceReference1.getAllCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllCategoriesRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllCategoriesResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllCategoriesResponse> getAllCategoriesAsync(MusicShopClient.ServiceReference1.getAllCategoriesRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewOrderRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MusicShopClient.ServiceReference1.addNewOrderResponse addNewOrder(MusicShopClient.ServiceReference1.addNewOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewOrderRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewOrderResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewOrderResponse> addNewOrderAsync(MusicShopClient.ServiceReference1.addNewOrderRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/removeProductRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/removeProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MusicShopClient.ServiceReference1.removeProductResponse removeProduct(MusicShopClient.ServiceReference1.removeProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/removeProductRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/removeProductResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.removeProductResponse> removeProductAsync(MusicShopClient.ServiceReference1.removeProductRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewCategoryRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewCategoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MusicShopClient.ServiceReference1.addNewCategoryResponse addNewCategory(MusicShopClient.ServiceReference1.addNewCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewCategoryRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewCategoryResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewCategoryResponse> addNewCategoryAsync(MusicShopClient.ServiceReference1.addNewCategoryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllProductsRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllProductsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MusicShopClient.ServiceReference1.getAllProductsResponse getAllProducts(MusicShopClient.ServiceReference1.getAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllProductsRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllProductsResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllProductsResponse> getAllProductsAsync(MusicShopClient.ServiceReference1.getAllProductsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllOrdersRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllOrdersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MusicShopClient.ServiceReference1.getAllOrdersResponse getAllOrders(MusicShopClient.ServiceReference1.getAllOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllOrdersRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllOrdersResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllOrdersResponse> getAllOrdersAsync(MusicShopClient.ServiceReference1.getAllOrdersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllUsersRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllUsersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MusicShopClient.ServiceReference1.getAllUsersResponse getAllUsers(MusicShopClient.ServiceReference1.getAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllUsersRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllUsersResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllUsersResponse> getAllUsersAsync(MusicShopClient.ServiceReference1.getAllUsersRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewProductRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MusicShopClient.ServiceReference1.addNewProductResponse addNewProduct(MusicShopClient.ServiceReference1.addNewProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewProductRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewProductResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewProductResponse> addNewProductAsync(MusicShopClient.ServiceReference1.addNewProductRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/")]
    public partial class categories : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal catIdField;
        
        private bool catIdFieldSpecified;
        
        private string catNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal catId {
            get {
                return this.catIdField;
            }
            set {
                this.catIdField = value;
                this.RaisePropertyChanged("catId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool catIdSpecified {
            get {
                return this.catIdFieldSpecified;
            }
            set {
                this.catIdFieldSpecified = value;
                this.RaisePropertyChanged("catIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string catName {
            get {
                return this.catNameField;
            }
            set {
                this.catNameField = value;
                this.RaisePropertyChanged("catName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/")]
    public partial class users : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usrFirstNameField;
        
        private decimal usrIdField;
        
        private bool usrIdFieldSpecified;
        
        private string usrIsActiveField;
        
        private string usrLastNameField;
        
        private string usrLoginField;
        
        private string usrPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string usrFirstName {
            get {
                return this.usrFirstNameField;
            }
            set {
                this.usrFirstNameField = value;
                this.RaisePropertyChanged("usrFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal usrId {
            get {
                return this.usrIdField;
            }
            set {
                this.usrIdField = value;
                this.RaisePropertyChanged("usrId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usrIdSpecified {
            get {
                return this.usrIdFieldSpecified;
            }
            set {
                this.usrIdFieldSpecified = value;
                this.RaisePropertyChanged("usrIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string usrIsActive {
            get {
                return this.usrIsActiveField;
            }
            set {
                this.usrIsActiveField = value;
                this.RaisePropertyChanged("usrIsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string usrLastName {
            get {
                return this.usrLastNameField;
            }
            set {
                this.usrLastNameField = value;
                this.RaisePropertyChanged("usrLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string usrLogin {
            get {
                return this.usrLoginField;
            }
            set {
                this.usrLoginField = value;
                this.RaisePropertyChanged("usrLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string usrPassword {
            get {
                return this.usrPasswordField;
            }
            set {
                this.usrPasswordField = value;
                this.RaisePropertyChanged("usrPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/")]
    public partial class orders : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime ordCompletedDateField;
        
        private bool ordCompletedDateFieldSpecified;
        
        private decimal ordIdField;
        
        private bool ordIdFieldSpecified;
        
        private string ordIsCompletedField;
        
        private string ordIsPaidField;
        
        private System.DateTime ordOrderDateField;
        
        private bool ordOrderDateFieldSpecified;
        
        private System.DateTime ordPaiedDateField;
        
        private bool ordPaiedDateFieldSpecified;
        
        private decimal ordTotalPriceField;
        
        private bool ordTotalPriceFieldSpecified;
        
        private users ordUsrIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime ordCompletedDate {
            get {
                return this.ordCompletedDateField;
            }
            set {
                this.ordCompletedDateField = value;
                this.RaisePropertyChanged("ordCompletedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordCompletedDateSpecified {
            get {
                return this.ordCompletedDateFieldSpecified;
            }
            set {
                this.ordCompletedDateFieldSpecified = value;
                this.RaisePropertyChanged("ordCompletedDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal ordId {
            get {
                return this.ordIdField;
            }
            set {
                this.ordIdField = value;
                this.RaisePropertyChanged("ordId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordIdSpecified {
            get {
                return this.ordIdFieldSpecified;
            }
            set {
                this.ordIdFieldSpecified = value;
                this.RaisePropertyChanged("ordIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ordIsCompleted {
            get {
                return this.ordIsCompletedField;
            }
            set {
                this.ordIsCompletedField = value;
                this.RaisePropertyChanged("ordIsCompleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ordIsPaid {
            get {
                return this.ordIsPaidField;
            }
            set {
                this.ordIsPaidField = value;
                this.RaisePropertyChanged("ordIsPaid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime ordOrderDate {
            get {
                return this.ordOrderDateField;
            }
            set {
                this.ordOrderDateField = value;
                this.RaisePropertyChanged("ordOrderDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordOrderDateSpecified {
            get {
                return this.ordOrderDateFieldSpecified;
            }
            set {
                this.ordOrderDateFieldSpecified = value;
                this.RaisePropertyChanged("ordOrderDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime ordPaiedDate {
            get {
                return this.ordPaiedDateField;
            }
            set {
                this.ordPaiedDateField = value;
                this.RaisePropertyChanged("ordPaiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordPaiedDateSpecified {
            get {
                return this.ordPaiedDateFieldSpecified;
            }
            set {
                this.ordPaiedDateFieldSpecified = value;
                this.RaisePropertyChanged("ordPaiedDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ordTotalPrice {
            get {
                return this.ordTotalPriceField;
            }
            set {
                this.ordTotalPriceField = value;
                this.RaisePropertyChanged("ordTotalPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordTotalPriceSpecified {
            get {
                return this.ordTotalPriceFieldSpecified;
            }
            set {
                this.ordTotalPriceFieldSpecified = value;
                this.RaisePropertyChanged("ordTotalPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public users ordUsrId {
            get {
                return this.ordUsrIdField;
            }
            set {
                this.ordUsrIdField = value;
                this.RaisePropertyChanged("ordUsrId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/")]
    public partial class products : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long prdAmountField;
        
        private categories prdCatIdField;
        
        private string prdDescriptionField;
        
        private decimal prdIdField;
        
        private bool prdIdFieldSpecified;
        
        private string prdNameField;
        
        private decimal prdPriceField;
        
        private bool prdPriceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long prdAmount {
            get {
                return this.prdAmountField;
            }
            set {
                this.prdAmountField = value;
                this.RaisePropertyChanged("prdAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public categories prdCatId {
            get {
                return this.prdCatIdField;
            }
            set {
                this.prdCatIdField = value;
                this.RaisePropertyChanged("prdCatId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string prdDescription {
            get {
                return this.prdDescriptionField;
            }
            set {
                this.prdDescriptionField = value;
                this.RaisePropertyChanged("prdDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal prdId {
            get {
                return this.prdIdField;
            }
            set {
                this.prdIdField = value;
                this.RaisePropertyChanged("prdId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prdIdSpecified {
            get {
                return this.prdIdFieldSpecified;
            }
            set {
                this.prdIdFieldSpecified = value;
                this.RaisePropertyChanged("prdIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string prdName {
            get {
                return this.prdNameField;
            }
            set {
                this.prdNameField = value;
                this.RaisePropertyChanged("prdName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal prdPrice {
            get {
                return this.prdPriceField;
            }
            set {
                this.prdPriceField = value;
                this.RaisePropertyChanged("prdPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prdPriceSpecified {
            get {
                return this.prdPriceFieldSpecified;
            }
            set {
                this.prdPriceFieldSpecified = value;
                this.RaisePropertyChanged("prdPriceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCategories", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllCategoriesRequest {
        
        public getAllCategoriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCategoriesResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MusicShopClient.ServiceReference1.categories[] @return;
        
        public getAllCategoriesResponse() {
        }
        
        public getAllCategoriesResponse(MusicShopClient.ServiceReference1.categories[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewOrder", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class addNewOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime orderDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime paymentDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime completedDate;
        
        public addNewOrderRequest() {
        }
        
        public addNewOrderRequest(int id, string userLogin, string productName, System.DateTime orderDate, System.DateTime paymentDate, System.DateTime completedDate) {
            this.id = id;
            this.userLogin = userLogin;
            this.productName = productName;
            this.orderDate = orderDate;
            this.paymentDate = paymentDate;
            this.completedDate = completedDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewOrderResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class addNewOrderResponse {
        
        public addNewOrderResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeProduct", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class removeProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public removeProductRequest() {
        }
        
        public removeProductRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeProductResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class removeProductResponse {
        
        public removeProductResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewCategory", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class addNewCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public addNewCategoryRequest() {
        }
        
        public addNewCategoryRequest(int id, string name) {
            this.id = id;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewCategoryResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class addNewCategoryResponse {
        
        public addNewCategoryResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllProducts", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllProductsRequest {
        
        public getAllProductsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllProductsResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MusicShopClient.ServiceReference1.products[] @return;
        
        public getAllProductsResponse() {
        }
        
        public getAllProductsResponse(MusicShopClient.ServiceReference1.products[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllOrders", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllOrdersRequest {
        
        public getAllOrdersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllOrdersResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MusicShopClient.ServiceReference1.orders[] @return;
        
        public getAllOrdersResponse() {
        }
        
        public getAllOrdersResponse(MusicShopClient.ServiceReference1.orders[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllUsers", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllUsersRequest {
        
        public getAllUsersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllUsersResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MusicShopClient.ServiceReference1.users[] @return;
        
        public getAllUsersResponse() {
        }
        
        public getAllUsersResponse(MusicShopClient.ServiceReference1.users[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewProduct", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class addNewProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string catName;
        
        public addNewProductRequest() {
        }
        
        public addNewProductRequest(double id, string name, double price, long amount, string description, string catName) {
            this.id = id;
            this.name = name;
            this.price = price;
            this.amount = amount;
            this.description = description;
            this.catName = catName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewProductResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class addNewProductResponse {
        
        public addNewProductResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MusicShopWebServiceChannel : MusicShopClient.ServiceReference1.MusicShopWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusicShopWebServiceClient : System.ServiceModel.ClientBase<MusicShopClient.ServiceReference1.MusicShopWebService>, MusicShopClient.ServiceReference1.MusicShopWebService {
        
        public MusicShopWebServiceClient() {
        }
        
        public MusicShopWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusicShopWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicShopWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicShopWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.getAllCategoriesResponse MusicShopClient.ServiceReference1.MusicShopWebService.getAllCategories(MusicShopClient.ServiceReference1.getAllCategoriesRequest request) {
            return base.Channel.getAllCategories(request);
        }
        
        public MusicShopClient.ServiceReference1.categories[] getAllCategories() {
            MusicShopClient.ServiceReference1.getAllCategoriesRequest inValue = new MusicShopClient.ServiceReference1.getAllCategoriesRequest();
            MusicShopClient.ServiceReference1.getAllCategoriesResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllCategories(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllCategoriesResponse> MusicShopClient.ServiceReference1.MusicShopWebService.getAllCategoriesAsync(MusicShopClient.ServiceReference1.getAllCategoriesRequest request) {
            return base.Channel.getAllCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllCategoriesResponse> getAllCategoriesAsync() {
            MusicShopClient.ServiceReference1.getAllCategoriesRequest inValue = new MusicShopClient.ServiceReference1.getAllCategoriesRequest();
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.addNewOrderResponse MusicShopClient.ServiceReference1.MusicShopWebService.addNewOrder(MusicShopClient.ServiceReference1.addNewOrderRequest request) {
            return base.Channel.addNewOrder(request);
        }
        
        public void addNewOrder(int id, string userLogin, string productName, System.DateTime orderDate, System.DateTime paymentDate, System.DateTime completedDate) {
            MusicShopClient.ServiceReference1.addNewOrderRequest inValue = new MusicShopClient.ServiceReference1.addNewOrderRequest();
            inValue.id = id;
            inValue.userLogin = userLogin;
            inValue.productName = productName;
            inValue.orderDate = orderDate;
            inValue.paymentDate = paymentDate;
            inValue.completedDate = completedDate;
            MusicShopClient.ServiceReference1.addNewOrderResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).addNewOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewOrderResponse> MusicShopClient.ServiceReference1.MusicShopWebService.addNewOrderAsync(MusicShopClient.ServiceReference1.addNewOrderRequest request) {
            return base.Channel.addNewOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewOrderResponse> addNewOrderAsync(int id, string userLogin, string productName, System.DateTime orderDate, System.DateTime paymentDate, System.DateTime completedDate) {
            MusicShopClient.ServiceReference1.addNewOrderRequest inValue = new MusicShopClient.ServiceReference1.addNewOrderRequest();
            inValue.id = id;
            inValue.userLogin = userLogin;
            inValue.productName = productName;
            inValue.orderDate = orderDate;
            inValue.paymentDate = paymentDate;
            inValue.completedDate = completedDate;
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).addNewOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.removeProductResponse MusicShopClient.ServiceReference1.MusicShopWebService.removeProduct(MusicShopClient.ServiceReference1.removeProductRequest request) {
            return base.Channel.removeProduct(request);
        }
        
        public void removeProduct(int id) {
            MusicShopClient.ServiceReference1.removeProductRequest inValue = new MusicShopClient.ServiceReference1.removeProductRequest();
            inValue.id = id;
            MusicShopClient.ServiceReference1.removeProductResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).removeProduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.removeProductResponse> MusicShopClient.ServiceReference1.MusicShopWebService.removeProductAsync(MusicShopClient.ServiceReference1.removeProductRequest request) {
            return base.Channel.removeProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.removeProductResponse> removeProductAsync(int id) {
            MusicShopClient.ServiceReference1.removeProductRequest inValue = new MusicShopClient.ServiceReference1.removeProductRequest();
            inValue.id = id;
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).removeProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.addNewCategoryResponse MusicShopClient.ServiceReference1.MusicShopWebService.addNewCategory(MusicShopClient.ServiceReference1.addNewCategoryRequest request) {
            return base.Channel.addNewCategory(request);
        }
        
        public void addNewCategory(int id, string name) {
            MusicShopClient.ServiceReference1.addNewCategoryRequest inValue = new MusicShopClient.ServiceReference1.addNewCategoryRequest();
            inValue.id = id;
            inValue.name = name;
            MusicShopClient.ServiceReference1.addNewCategoryResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).addNewCategory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewCategoryResponse> MusicShopClient.ServiceReference1.MusicShopWebService.addNewCategoryAsync(MusicShopClient.ServiceReference1.addNewCategoryRequest request) {
            return base.Channel.addNewCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewCategoryResponse> addNewCategoryAsync(int id, string name) {
            MusicShopClient.ServiceReference1.addNewCategoryRequest inValue = new MusicShopClient.ServiceReference1.addNewCategoryRequest();
            inValue.id = id;
            inValue.name = name;
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).addNewCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.getAllProductsResponse MusicShopClient.ServiceReference1.MusicShopWebService.getAllProducts(MusicShopClient.ServiceReference1.getAllProductsRequest request) {
            return base.Channel.getAllProducts(request);
        }
        
        public MusicShopClient.ServiceReference1.products[] getAllProducts() {
            MusicShopClient.ServiceReference1.getAllProductsRequest inValue = new MusicShopClient.ServiceReference1.getAllProductsRequest();
            MusicShopClient.ServiceReference1.getAllProductsResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllProducts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllProductsResponse> MusicShopClient.ServiceReference1.MusicShopWebService.getAllProductsAsync(MusicShopClient.ServiceReference1.getAllProductsRequest request) {
            return base.Channel.getAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllProductsResponse> getAllProductsAsync() {
            MusicShopClient.ServiceReference1.getAllProductsRequest inValue = new MusicShopClient.ServiceReference1.getAllProductsRequest();
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.getAllOrdersResponse MusicShopClient.ServiceReference1.MusicShopWebService.getAllOrders(MusicShopClient.ServiceReference1.getAllOrdersRequest request) {
            return base.Channel.getAllOrders(request);
        }
        
        public MusicShopClient.ServiceReference1.orders[] getAllOrders() {
            MusicShopClient.ServiceReference1.getAllOrdersRequest inValue = new MusicShopClient.ServiceReference1.getAllOrdersRequest();
            MusicShopClient.ServiceReference1.getAllOrdersResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllOrders(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllOrdersResponse> MusicShopClient.ServiceReference1.MusicShopWebService.getAllOrdersAsync(MusicShopClient.ServiceReference1.getAllOrdersRequest request) {
            return base.Channel.getAllOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllOrdersResponse> getAllOrdersAsync() {
            MusicShopClient.ServiceReference1.getAllOrdersRequest inValue = new MusicShopClient.ServiceReference1.getAllOrdersRequest();
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.getAllUsersResponse MusicShopClient.ServiceReference1.MusicShopWebService.getAllUsers(MusicShopClient.ServiceReference1.getAllUsersRequest request) {
            return base.Channel.getAllUsers(request);
        }
        
        public MusicShopClient.ServiceReference1.users[] getAllUsers() {
            MusicShopClient.ServiceReference1.getAllUsersRequest inValue = new MusicShopClient.ServiceReference1.getAllUsersRequest();
            MusicShopClient.ServiceReference1.getAllUsersResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllUsers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllUsersResponse> MusicShopClient.ServiceReference1.MusicShopWebService.getAllUsersAsync(MusicShopClient.ServiceReference1.getAllUsersRequest request) {
            return base.Channel.getAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllUsersResponse> getAllUsersAsync() {
            MusicShopClient.ServiceReference1.getAllUsersRequest inValue = new MusicShopClient.ServiceReference1.getAllUsersRequest();
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.addNewProductResponse MusicShopClient.ServiceReference1.MusicShopWebService.addNewProduct(MusicShopClient.ServiceReference1.addNewProductRequest request) {
            return base.Channel.addNewProduct(request);
        }
        
        public void addNewProduct(double id, string name, double price, long amount, string description, string catName) {
            MusicShopClient.ServiceReference1.addNewProductRequest inValue = new MusicShopClient.ServiceReference1.addNewProductRequest();
            inValue.id = id;
            inValue.name = name;
            inValue.price = price;
            inValue.amount = amount;
            inValue.description = description;
            inValue.catName = catName;
            MusicShopClient.ServiceReference1.addNewProductResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).addNewProduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewProductResponse> MusicShopClient.ServiceReference1.MusicShopWebService.addNewProductAsync(MusicShopClient.ServiceReference1.addNewProductRequest request) {
            return base.Channel.addNewProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewProductResponse> addNewProductAsync(double id, string name, double price, long amount, string description, string catName) {
            MusicShopClient.ServiceReference1.addNewProductRequest inValue = new MusicShopClient.ServiceReference1.addNewProductRequest();
            inValue.id = id;
            inValue.name = name;
            inValue.price = price;
            inValue.amount = amount;
            inValue.description = description;
            inValue.catName = catName;
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).addNewProductAsync(inValue);
        }
    }
}
