//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicShopClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", ConfigurationName="ServiceReference1.MusicShopWebService")]
    public interface MusicShopWebService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllCategoriesRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllCategoriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MusicShopClient.ServiceReference1.getAllCategoriesResponse getAllCategories(MusicShopClient.ServiceReference1.getAllCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllCategoriesRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllCategoriesResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllCategoriesResponse> getAllCategoriesAsync(MusicShopClient.ServiceReference1.getAllCategoriesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/helloRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MusicShopClient.ServiceReference1.helloResponse hello(MusicShopClient.ServiceReference1.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/helloRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/helloResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.helloResponse> helloAsync(MusicShopClient.ServiceReference1.helloRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewProductRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MusicShopClient.ServiceReference1.addNewProductResponse addNewProduct(MusicShopClient.ServiceReference1.addNewProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewProductRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/addNewProductResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewProductResponse> addNewProductAsync(MusicShopClient.ServiceReference1.addNewProductRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllProductsRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllProductsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MusicShopClient.ServiceReference1.getAllProductsResponse getAllProducts(MusicShopClient.ServiceReference1.getAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllProductsRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/getAllProductsResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllProductsResponse> getAllProductsAsync(MusicShopClient.ServiceReference1.getAllProductsRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/removeProductRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/removeProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MusicShopClient.ServiceReference1.removeProductResponse removeProduct(MusicShopClient.ServiceReference1.removeProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/removeProductRequest", ReplyAction="http://ws.musicshopapp.pai.lodz.pl/MusicShopWebService/removeProductResponse")]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.removeProductResponse> removeProductAsync(MusicShopClient.ServiceReference1.removeProductRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/")]
    public partial class categories : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal catIdField;
        
        private bool catIdFieldSpecified;
        
        private string catNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal catId {
            get {
                return this.catIdField;
            }
            set {
                this.catIdField = value;
                this.RaisePropertyChanged("catId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool catIdSpecified {
            get {
                return this.catIdFieldSpecified;
            }
            set {
                this.catIdFieldSpecified = value;
                this.RaisePropertyChanged("catIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string catName {
            get {
                return this.catNameField;
            }
            set {
                this.catNameField = value;
                this.RaisePropertyChanged("catName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/")]
    public partial class products : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long prdAmountField;
        
        private categories prdCatIdField;
        
        private string prdDescriptionField;
        
        private decimal prdIdField;
        
        private bool prdIdFieldSpecified;
        
        private string prdNameField;
        
        private decimal prdPriceField;
        
        private bool prdPriceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long prdAmount {
            get {
                return this.prdAmountField;
            }
            set {
                this.prdAmountField = value;
                this.RaisePropertyChanged("prdAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public categories prdCatId {
            get {
                return this.prdCatIdField;
            }
            set {
                this.prdCatIdField = value;
                this.RaisePropertyChanged("prdCatId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string prdDescription {
            get {
                return this.prdDescriptionField;
            }
            set {
                this.prdDescriptionField = value;
                this.RaisePropertyChanged("prdDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal prdId {
            get {
                return this.prdIdField;
            }
            set {
                this.prdIdField = value;
                this.RaisePropertyChanged("prdId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prdIdSpecified {
            get {
                return this.prdIdFieldSpecified;
            }
            set {
                this.prdIdFieldSpecified = value;
                this.RaisePropertyChanged("prdIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string prdName {
            get {
                return this.prdNameField;
            }
            set {
                this.prdNameField = value;
                this.RaisePropertyChanged("prdName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal prdPrice {
            get {
                return this.prdPriceField;
            }
            set {
                this.prdPriceField = value;
                this.RaisePropertyChanged("prdPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prdPriceSpecified {
            get {
                return this.prdPriceFieldSpecified;
            }
            set {
                this.prdPriceFieldSpecified = value;
                this.RaisePropertyChanged("prdPriceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCategories", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllCategoriesRequest {
        
        public getAllCategoriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCategoriesResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MusicShopClient.ServiceReference1.categories[] @return;
        
        public getAllCategoriesResponse() {
        }
        
        public getAllCategoriesResponse(MusicShopClient.ServiceReference1.categories[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewProduct", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class addNewProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long amount;
        
        public addNewProductRequest() {
        }
        
        public addNewProductRequest(decimal id, string name, decimal price, long amount) {
            this.id = id;
            this.name = name;
            this.price = price;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addNewProductResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class addNewProductResponse {
        
        public addNewProductResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllProducts", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllProductsRequest {
        
        public getAllProductsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllProductsResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class getAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MusicShopClient.ServiceReference1.products[] @return;
        
        public getAllProductsResponse() {
        }
        
        public getAllProductsResponse(MusicShopClient.ServiceReference1.products[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeProduct", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class removeProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.musicshopapp.pai.lodz.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public removeProductRequest() {
        }
        
        public removeProductRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeProductResponse", WrapperNamespace="http://ws.musicshopapp.pai.lodz.pl/", IsWrapped=true)]
    public partial class removeProductResponse {
        
        public removeProductResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MusicShopWebServiceChannel : MusicShopClient.ServiceReference1.MusicShopWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusicShopWebServiceClient : System.ServiceModel.ClientBase<MusicShopClient.ServiceReference1.MusicShopWebService>, MusicShopClient.ServiceReference1.MusicShopWebService {
        
        public MusicShopWebServiceClient() {
        }
        
        public MusicShopWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusicShopWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicShopWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicShopWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.getAllCategoriesResponse MusicShopClient.ServiceReference1.MusicShopWebService.getAllCategories(MusicShopClient.ServiceReference1.getAllCategoriesRequest request) {
            return base.Channel.getAllCategories(request);
        }
        
        public MusicShopClient.ServiceReference1.categories[] getAllCategories() {
            MusicShopClient.ServiceReference1.getAllCategoriesRequest inValue = new MusicShopClient.ServiceReference1.getAllCategoriesRequest();
            MusicShopClient.ServiceReference1.getAllCategoriesResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllCategories(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllCategoriesResponse> MusicShopClient.ServiceReference1.MusicShopWebService.getAllCategoriesAsync(MusicShopClient.ServiceReference1.getAllCategoriesRequest request) {
            return base.Channel.getAllCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllCategoriesResponse> getAllCategoriesAsync() {
            MusicShopClient.ServiceReference1.getAllCategoriesRequest inValue = new MusicShopClient.ServiceReference1.getAllCategoriesRequest();
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.helloResponse MusicShopClient.ServiceReference1.MusicShopWebService.hello(MusicShopClient.ServiceReference1.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            MusicShopClient.ServiceReference1.helloRequest inValue = new MusicShopClient.ServiceReference1.helloRequest();
            inValue.name = name;
            MusicShopClient.ServiceReference1.helloResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.helloResponse> MusicShopClient.ServiceReference1.MusicShopWebService.helloAsync(MusicShopClient.ServiceReference1.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.helloResponse> helloAsync(string name) {
            MusicShopClient.ServiceReference1.helloRequest inValue = new MusicShopClient.ServiceReference1.helloRequest();
            inValue.name = name;
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.addNewProductResponse MusicShopClient.ServiceReference1.MusicShopWebService.addNewProduct(MusicShopClient.ServiceReference1.addNewProductRequest request) {
            return base.Channel.addNewProduct(request);
        }
        
        public void addNewProduct(decimal id, string name, decimal price, long amount) {
            MusicShopClient.ServiceReference1.addNewProductRequest inValue = new MusicShopClient.ServiceReference1.addNewProductRequest();
            inValue.id = id;
            inValue.name = name;
            inValue.price = price;
            inValue.amount = amount;
            MusicShopClient.ServiceReference1.addNewProductResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).addNewProduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewProductResponse> MusicShopClient.ServiceReference1.MusicShopWebService.addNewProductAsync(MusicShopClient.ServiceReference1.addNewProductRequest request) {
            return base.Channel.addNewProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.addNewProductResponse> addNewProductAsync(decimal id, string name, decimal price, long amount) {
            MusicShopClient.ServiceReference1.addNewProductRequest inValue = new MusicShopClient.ServiceReference1.addNewProductRequest();
            inValue.id = id;
            inValue.name = name;
            inValue.price = price;
            inValue.amount = amount;
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).addNewProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.getAllProductsResponse MusicShopClient.ServiceReference1.MusicShopWebService.getAllProducts(MusicShopClient.ServiceReference1.getAllProductsRequest request) {
            return base.Channel.getAllProducts(request);
        }
        
        public MusicShopClient.ServiceReference1.products[] getAllProducts() {
            MusicShopClient.ServiceReference1.getAllProductsRequest inValue = new MusicShopClient.ServiceReference1.getAllProductsRequest();
            MusicShopClient.ServiceReference1.getAllProductsResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllProducts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllProductsResponse> MusicShopClient.ServiceReference1.MusicShopWebService.getAllProductsAsync(MusicShopClient.ServiceReference1.getAllProductsRequest request) {
            return base.Channel.getAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.getAllProductsResponse> getAllProductsAsync() {
            MusicShopClient.ServiceReference1.getAllProductsRequest inValue = new MusicShopClient.ServiceReference1.getAllProductsRequest();
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).getAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MusicShopClient.ServiceReference1.removeProductResponse MusicShopClient.ServiceReference1.MusicShopWebService.removeProduct(MusicShopClient.ServiceReference1.removeProductRequest request) {
            return base.Channel.removeProduct(request);
        }
        
        public void removeProduct(int id) {
            MusicShopClient.ServiceReference1.removeProductRequest inValue = new MusicShopClient.ServiceReference1.removeProductRequest();
            inValue.id = id;
            MusicShopClient.ServiceReference1.removeProductResponse retVal = ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).removeProduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.removeProductResponse> MusicShopClient.ServiceReference1.MusicShopWebService.removeProductAsync(MusicShopClient.ServiceReference1.removeProductRequest request) {
            return base.Channel.removeProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<MusicShopClient.ServiceReference1.removeProductResponse> removeProductAsync(int id) {
            MusicShopClient.ServiceReference1.removeProductRequest inValue = new MusicShopClient.ServiceReference1.removeProductRequest();
            inValue.id = id;
            return ((MusicShopClient.ServiceReference1.MusicShopWebService)(this)).removeProductAsync(inValue);
        }
    }
}
